config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  
  root 'home#index'
  get 'home/index'
  get 'home/search'
  get 'home/list'
  get 'home/reviews'
 
  resources :post, except: [:index] do
    resources :review
    get 'like_toggle', as: 'like', on: :member
    
  end
  
  post 'match/m_request'
  post 'match/m_accept'
  post 'match/m_decline'
  
  get 'mypage/mypost'
  get 'mypage/mylike'
  get 'mypage/manage_users'
  get 'mypage/matched_users'
  

end

app/models/about.rb
class About < ActiveRecord::Base
  belongs_to :post
  belongs_to :hashtag
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :interests
  has_many :interested_users, through: :interests, source: :user
  has_many :posts
end

app/models/hashtag.rb
class Hashtag < ActiveRecord::Base
  has_many :abouts
  has_many :related_posts, through: :abouts, source: :post
end

app/models/interest.rb
class Interest < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
end

app/models/like.rb
class Like < ActiveRecord::Base
    belongs_to :user
    belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  belongs_to :user
  belongs_to :category
  has_many :likes
  has_many :liked_users, through: :likes, source: :user
  has_many :abouts
  has_many :related_hashtags, through: :abouts, source: :hashtag
  has_many :reviews
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/user.rb
class User < ActiveRecord::Base
  has_friendship
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :interests
  has_many :interested_categories, through: :interests, source: :category
  
  has_many :posts
  has_many :likes
  has_many :liked_posts, through: :likes, source: :post
  has_many :reviews
  
  def is_like?(post)
    Like.find_by(user_id: self.id, post_id: post.id).present?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    unless user_signed_in?
      redirect_to '/users/sign_in'
    end
  end
  
  def list
    @posts = Post.all
  end
  
  def reviews
    @reviews= Review.all
  end
end

app/controllers/like_controller.rb
class LikeController < ApplicationController
  before_action :authenticate_user

  
  def like_toggle
    like = Like.find_by(user_id: currrent_user.id, post_id: params[:post_id])
    if like.nil?
      Like.create(user_id: currrent_user.id, post_id: params[:post_id])
    else
      like.destroy
    end
    redirect_to :back
  end
end

app/controllers/match_controller.rb
class MatchController < ApplicationController
  def m_request
    current_user.friend_request(User.find(params[:user_id]))
    redirect_to :back
  end
  def m_accept
    current_user.accept_request(User.find(params[:user_id]))
    redirect_to :back
  end
  def m_decline
    current_user.decline_request(User.find(params[:user_id]))
    redirect_to :back
  end

end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController
  def mypost
    @posts = current_user.posts
  end
  
  def mylike
    @posts = current_user.liked_posts
  end
  
  def manage_users #나에게 온 요청, 내가 보낸 요청
    @requested_friends = current_user.requested_friends
    @pending_friends = current_user.pending_friends
  end
  
  def matched_users #매칭된 유저
    @friends = current_user.friends
  end
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  require 'carrierwave/orm/activerecord'
  before_action :authenticate_user!, only: [:show, :new, :create, :edit, :update, :destroy]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  
  def new
    @post = Post.new
    @categories = Category.all
  end
  
  def create
    post = Post.create(post_params)
    post.image = params[:image]
    post.save!

    redirect_to '/'
  end
  
  def show
    @review = Review.new
  end
  
  def edit
  end
  
  def update
    Post.update(post_params)
    redirect_to root_path
  end
  
  def destroy
    @post.destroy
    redirect_to root_path
  end
  
  def like_toggle
    like = Like.find_by(user_id: current_user.id, post_id: params[:id]) 
    
    if like.nil?
      Like.create(user_id: current_user.id, post_id: params[:id])
    else
      like.destroy
    end
    redirect_to :back
  end
  private
  
  def post_params
    params.require(:post).permit(:title, :content, :image, :category_id, :user_id)
    
  end
  
  def set_post
    @post = Post.find(params[:id])
  end
  
end

app/controllers/review_controller.rb
class ReviewController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_review, only: [:edit, :update, :destroy]
  
  def new
    @review = Review.new
  end
  
  def create
    review = Review.create(review_params)
    redirect_to :back
  end
  
  def edit
  end
  
  def update
    Review.update(review_params)
    redirect_to root_path
  end
  
  def destroy
    @review.destroy
    redirect_to root_path  
  end
  
  
  private
  
  def review_params
    params.require(:review).permit(:content, :user_id, :post_id)
  end
  
  def set_review
    @review = Review.find(params[:review_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/interest_helper.rb
module InterestHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/match_helper.rb
module MatchHelper
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/views/home/index.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="4"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag "01-01.jpg",class: "d-block w-100", alt: "First slide", height: "20%" %>
    </div>
    <div class="carousel-item">
      <%= image_tag "01-02.jpg",class: "d-block w-100", alt: "Second slide", height: "20%" %>
    </div>
    <div class="carousel-item">
      <%= image_tag "01-03.jpg",class: "d-block w-100", alt: "Third slide", height: "20%" %>
    </div>
    <div class="carousel-item">
      <%= image_tag "01-04.jpg",class: "d-block w-100", alt: "Fourth slide", height: "20%" %>
    </div>
    <div class="carousel-item">
      <%= image_tag "01-05.jpg",class: "d-block w-100", alt: "Fifth slide", height: "20%" %>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
<script>
  $(function(){
	  $('footer').css('display', 'flex');
  });
</script>

app/views/home/list.html.erb
<div class="posts-container">
  <i class="fas fa-edit">
  <a href="/post/new" class="btn btn-secondary" role="button" aria-pressed="true">글쓰기</a></i><br>
  <section class="row post-section">
    <% @posts.each do |p| %>
      <article class="post-card col-12 col-md-3 <%= 'senior-card' if p.user.position == "senior" %>">
        <h2><%= link_to p.title, post_path(p.id), class: "post-title" %></h2>
        <p><%#= p.category.content %></p>
        <p class="post-nickname"><%= p.user.nickname %></p>
        <%if user_signed_in? %>
          <%= link_to like_post_path(p), method: "get" do %>
            <% if current_user.is_like?(p) %>
              <i class="fas fa-heart"></i> <%= p.likes.size %>
            <% else %>
              <i class="far fa-heart"></i> <%= p.likes.size %>
            <% end %>
          <% end %>
        <% end %>
      </article>
    <% end %>
  </section>
</div>

app/views/home/reviews.html.erb
<div align='center'>
  <% @reviews.each do |p| %>
    <article class="review-card col-12 <%= 'senior-card' if p.user.position == "senior" %>" align='left'>
      <p class="post-nickname"><%= p.user.nickname %> > <span><%=p.post.user.nickname%>(<%=link_to p.post.title, post_path(p.post.id)%>)</span></p>
      <p><%=p.content %></p>
    </article>
  <% end %>
</div>

app/views/mypage/_menubar.html.erb
<nav class="navbar">
  <ul class="" style="margin-bottom: 0.5rem;">
    <li class="mypost"><%=link_to '내가 쓴 글', mypage_mypost_path, class: "#{'current-nav' if current_page?(mypage_mypost_path)}"%></li>
    <li class="mylike"><%=link_to '찜한 글', mypage_mylike_path, class: "#{'current-nav' if current_page?(mypage_mylike_path)}"%></li>
    <li class="manage_users"><%=link_to '매칭요청관리', mypage_manage_users_path, class: "#{'current-nav' if current_page?(mypage_manage_users_path)}"%></li>
    <li class="matched_users"><%=link_to '매칭된 유저',mypage_matched_users_path, class: "#{'current-nav' if current_page?(mypage_matched_users_path)}"%></li>
  </ul>
</nav>

<!--<script>-->
<!--  var flag = window.location.href.split('mypage/')[1];-->
<!--  $(function(){-->
<!--    $(flag).addClass('.current-nav');-->
<!--  });-->
<!--</script>-->

app/views/mypage/manage_users.html.erb
<div class="container">
  <%= render partial: "mypage/menubar" %>
  <hr>
  <div class='mt-30'></div>
  <div class='row'>
    <div class='mf-1'>
      <h2 class='gray'>매칭 요청</h2>
      <div class="f-card">
        <%@requested_friends.each do |f|%>
          <p><%=f.nickname%></p>
          <div class="flex-right">
            <%=form_tag(match_m_accept_path, method: "post", class: 'inline-block mr-10') do%>
              <%= hidden_field_tag(:user_id, f.id) %>
              <%= submit_tag("수락하기", class: 'matching-btn inline-block') %>
            <%end%>
            <%=form_tag(match_m_decline_path, method: "post", class: 'inline-block') do%>
              <%= hidden_field_tag(:user_id, f.id) %>
              <%= submit_tag("거절하기", class: 'matching-btn inline-block') %>
            <%end%>
          </div>  
        <%end%>
      </div>
    </div>  
    
    <div class='mf-2'>
      <h2 class='gray'>매칭 대기</h2>
      
      <%@pending_friends.each do |f|%>
        <div class="f-card">
          <%=f.nickname%><br>
        </div>
      <%end%>
    </div>  
    
  </div>
  
</div>

app/views/mypage/matched_users.html.erb
<div class='container'>
  <%= render partial: "mypage/menubar" %>
  <hr>
  <div class='mt-30'></div>
  <div align='center'>
    <% @friends.each do |f| %>
      <article class="review-card col-12 <%= 'senior-card' if f.position == "senior" %>" align='left'>
        <p></p>
        <p><%=f.nickname %></p>
        <h5><%=f.position %></h5>
      </article>
    <% end %>
  </div>
</div>

app/views/mypage/mylike.html.erb
<div class='container'>
  <%= render partial: "mypage/menubar" %>
  <hr>
  <div class='mt-30'></div>
  <div class="posts-container mt-20">
    <section class="row post-section">
      <%@posts.each do |p|%>
        <article class="post-card col-12 col-md-3 <%= 'senior-card' if p.user.position == "senior" %>">
          <h2><%= link_to p.title, post_path(p.id), class: "post-title" %></h2>
          <p><%#= p.category.content %></p>
          <p class="post-nickname"><%= p.user.nickname %></p>
          <%if user_signed_in? %>
            <%= link_to like_post_path(p), method: "get" do %>
              <% if current_user.is_like?(p) %>
                <i class="fas fa-heart"></i> <%= p.likes.size %>
              <% else %>
                <i class="far fa-heart"></i> <%= p.likes.size %>
              <% end %>
            <% end %>
          <% end %>
        </article>
      <%end%>
    </section>
  </div>
</div>

app/views/mypage/mypost.html.erb
<div class='container'>
  <%= render partial: "mypage/menubar" %>
  <hr>
  <div class='mt-30'></div>
  <div class="posts-container mt-20">
    <section class="row post-section">
      <%@posts.each do |p|%>
        <article class="post-card col-12 col-md-3 <%= 'senior-card' if p.user.position == "senior" %>">
          <h2><%= link_to p.title, post_path(p.id), class: "post-title" %></h2>
          <p><%#= p.category.content %></p>
          <p class="post-nickname"><%= p.user.nickname %></p>
          <%if user_signed_in? %>
            <%= link_to like_post_path(p), method: "get" do %>
              <% if current_user.is_like?(p) %>
                <i class="fas fa-heart"></i> <%= p.likes.size %>
              <% else %>
                <i class="far fa-heart"></i> <%= p.likes.size %>
              <% end %>
            <% end %>
          <% end %>
        </article>
      <%end%>
    </section>
  </div>
</div>  

app/views/review/write.html.erb
<%= form_tag(post_review_index_path, method: "post") do %>
<%= text_field_tag(:q) %>
<%= text_area_tag(:message,"후기를 작성해주세요") %>