config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  
  root 'home#index'
  get 'home/index'
  get 'home/search'
  get 'home/list'
  get 'home/reviews'
 
  resources :post, except: [:index] do
    resources :review
    get 'like_toggle', as: 'like', on: :member
    
  end
  
  post 'match/m_request'
  post 'match/m_accept'
  post 'match/m_decline'
  
  get 'mypage/mypost'
  get 'mypage/mylike'
  get 'mypage/manage_users'
  get 'mypage/matched_users'
  

end

app/models/about.rb
class About < ActiveRecord::Base
  belongs_to :post
  belongs_to :hashtag
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :interests
  has_many :interested_users, through: :interests, source: :user
  has_many :posts
end

app/models/hashtag.rb
class Hashtag < ActiveRecord::Base
  has_many :abouts
  has_many :related_posts, through: :abouts, source: :post
end

app/models/interest.rb
class Interest < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
end

app/models/like.rb
class Like < ActiveRecord::Base
    belongs_to :user
    belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  belongs_to :user
  belongs_to :category
  has_many :likes
  has_many :liked_users, through: :likes, source: :user
  has_many :abouts
  has_many :related_hashtags, through: :abouts, source: :hashtag
  has_many :reviews
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/user.rb
class User < ActiveRecord::Base
  has_friendship
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :interests
  has_many :interested_categories, through: :interests, source: :category
  
  has_many :posts
  has_many :likes
  has_many :liked_posts, through: :likes, source: :post
  has_many :reviews
  
  def is_like?(post)
    Like.find_by(user_id: self.id, post_id: post.id).present?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    unless user_signed_in?
      redirect_to '/users/sign_in'
    end
  end
  
  def list
    @posts = Post.all
  end
  
  def reviews
    @reviews= Review.all
  end
end

app/controllers/interest_controller.rb
class InterestController < ApplicationController
end

app/controllers/like_controller.rb
class LikeController < ApplicationController
  before_action :authenticate_user

  
  def like_toggle
    like = Like.find_by(user_id: currrent_user.id, post_id: params[:post_id])
    if like.nil?
      Like.create(user_id: currrent_user.id, post_id: params[:post_id])
    else
      like.destroy
    end
    redirect_to :back
  end
end

app/controllers/match_controller.rb
class MatchController < ApplicationController
  def m_request
    current_user.friend_request(User.find(params[:user_id]))
    redirect_to :back
  end
  def m_accept
    current_user.accept_request(User.find(params[:user_id]))
    redirect_to :back
  end
  def m_decline
    current_user.decline_request(User.find(params[:user_id]))
    redirect_to :back
  end

end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController
  def mypost
    @posts = current_user.posts
  end
  
  def mylike
    @posts = current_user.liked_posts
  end
  
  def manage_users #나에게 온 요청, 내가 보낸 요청
    @requested_friends = current_user.requested_friends
    @pending_friends = current_user.pending_friends
  end
  
  def matched_users #매칭된 유저
    @friends = current_user.friends
  end
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  require 'carrierwave/orm/activerecord'
  before_action :authenticate_user!, only: [:show, :new, :create, :edit, :update, :destroy]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  
  def new
    @post = Post.new
    @categories = Category.all
  end
  
  def create
    post = Post.create(post_params)
    post.image = params[:image]
    post.save!

    redirect_to '/'
  end
  
  def show
    @review = Review.new
  end
  
  def edit
  end
  
  def update
    Post.update(post_params)
    redirect_to root_path
  end
  
  def destroy
    @post.destroy
    redirect_to root_path
  end
  
  def like_toggle
    like = Like.find_by(user_id: current_user.id, post_id: params[:id]) 
    
    if like.nil?
      Like.create(user_id: current_user.id, post_id: params[:id])
    else
      like.destroy
    end
    redirect_to :back
  end
  private
  
  def post_params
    params.require(:post).permit(:title, :content, :image, :category_id, :user_id)
    
  end
  
  def set_post
    @post = Post.find(params[:id])
  end
  
end

app/controllers/review_controller.rb
class ReviewController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_review, only: [:edit, :update, :destroy]
  
  def new
    @review = Review.new
  end
  
  def create
    review = Review.create(review_params)
    redirect_to :back
  end
  
  def edit
  end
  
  def update
    Review.update(review_params)
    redirect_to root_path
  end
  
  def destroy
    @review.destroy
    redirect_to root_path  
  end
  
  
  private
  
  def review_params
    params.require(:review).permit(:content, :user_id, :post_id)
  end
  
  def set_review
    @review = Review.find(params[:review_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/interest_helper.rb
module InterestHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/match_helper.rb
module MatchHelper
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/views/post/_post_form.html.erb
<form>
  <div class="form-group">
    <%= f.hidden_field :user_id, value: current_user.id %>
    <label for="exampleFormControlInput1">Title</label><br>
      <%= f.text_field :title, class: "form-control", id: "exampleFormControlInput1", style: "width: 50%", autocomplete: false %><br><br>
    <label for="exampleFormControlTextarea1">Content</label><br>
      <%= f.text_area :content, class: "form-control", id:"exampleFormControlTextarea1", rows: "10", style: "width: 50%", autocomplete: false %><br>
    <%= f.file_field :image, class: "post-file" %><br><br>
    <%= f.select(:category_id, 
      c.collect {|p| [ p.content, p.id] }) %>
    <%=f.hidden_field :user_id, value: "#{current_user.id}" %>
    <%#= f.select(:post, :category, [['Lisbon', 1], ['Madrid', 2], ...]) %>
    <%= f.submit "SUBMIT", class: "btn btn-secondary" %>
  </div>
</form>

app/views/post/new.html.erb
<div class="container post-form-section">
  <%= form_for @post, url: {action: "create"}, enctype: 'multipart/form-data' do |f| %>
    <%= render partial: "post/post_form", locals: { f: f, c: @categories } %>
  <% end %>
</div>

app/views/post/show.erb
<section class="container">
  <h2 class="post-title"><%= @post.title %></h2>
  <p class="post-category"><%= @post.category.content %></p>
  <p class="post-nickname"><%= @post.user.nickname %> 님</p>
  <div class="post-content">
    <p><%= @post.content %></p>
    <%= image_tag "#{@post.image.url}", class: "post-image" %>
    <!--<img src="<%#= @post.image.url %>">-->
  </div>
  <% unless current_user == @post.user %>
    <% if not current_user.pending_friends.include?(@post.user) %>  
      <%= form_tag(match_m_request_path, method: "post") do %>
        <%= hidden_field_tag(:user_id, @post.user.id) %>
        <%= submit_tag "Matching", class: "matching-btn" %>
      <% end %>
    <% else %>
      <%= button_tag "Waiting", class: "waiting-btn", disabled: true %>
    <% end %>
    <% if current_user.is_like?(@post) %>
      <%= link_to("좋아요 취소",like_post_path(@post), method: "get") %>
    <%else%>
      <%= link_to("좋아요",like_post_path(@post), method: "get")%>
    <% end %>
  <% end %>
  
  <% if current_user.friends_with?(@post.user)%>
    <%= form_for @review, url: post_review_index_path(@post) do |f| %>
      <%=f.hidden_field :user_id, value: "#{current_user.id}" %>
      <%=f.hidden_field :post_id, value: "#{@post.id}" %>
      <%= f.text_area :content, class: "review-input" %>
      <%= f.submit "Write", class: "review-btn" %>
    <% end %>
  <%end%>
  
  <% @post.reviews.each do |r|%>
    <%= r.content %><br>
  <% end %>

</section>