config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  
  root 'home#index'
  get 'home/index'
  get 'home/search'
  get 'home/list'
  get 'home/reviews'
 
  resources :post, except: [:index] do
    resources :review
    get 'like_toggle', as: 'like', on: :member
    
  end
  
  post 'match/m_request'
  post 'match/m_accept'
  post 'match/m_decline'
  
  get 'mypage/mypost'
  get 'mypage/mylike'
  get 'mypage/manage_users'
  get 'mypage/matched_users'
  

end

app/models/about.rb
class About < ActiveRecord::Base
  belongs_to :post
  belongs_to :hashtag
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :interests
  has_many :interested_users, through: :interests, source: :user
  has_many :posts
end

app/models/hashtag.rb
class Hashtag < ActiveRecord::Base
  has_many :abouts
  has_many :related_posts, through: :abouts, source: :post
end

app/models/interest.rb
class Interest < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
end

app/models/like.rb
class Like < ActiveRecord::Base
    belongs_to :user
    belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  belongs_to :user
  belongs_to :category
  has_many :likes
  has_many :liked_users, through: :likes, source: :user
  has_many :abouts
  has_many :related_hashtags, through: :abouts, source: :hashtag
  has_many :reviews
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/user.rb
class User < ActiveRecord::Base
  has_friendship
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :interests
  has_many :interested_categories, through: :interests, source: :category
  
  has_many :posts
  has_many :likes
  has_many :liked_posts, through: :likes, source: :post
  has_many :reviews
  
  def is_like?(post)
    Like.find_by(user_id: self.id, post_id: post.id).present?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    unless user_signed_in?
      redirect_to '/users/sign_in'
    end
  end
  
  def list
    @posts = Post.all
  end
  
  def reviews
    @reviews= Review.all
  end
end

app/controllers/like_controller.rb
class LikeController < ApplicationController
  before_action :authenticate_user

  
  def like_toggle
    like = Like.find_by(user_id: currrent_user.id, post_id: params[:post_id])
    if like.nil?
      Like.create(user_id: currrent_user.id, post_id: params[:post_id])
    else
      like.destroy
    end
    redirect_to :back
  end
end

app/controllers/match_controller.rb
class MatchController < ApplicationController
  def m_request
    current_user.friend_request(User.find(params[:user_id]))
    redirect_to :back
  end
  def m_accept
    current_user.accept_request(User.find(params[:user_id]))
    redirect_to :back
  end
  def m_decline
    current_user.decline_request(User.find(params[:user_id]))
    redirect_to :back
  end

end

app/controllers/post_controller.rb
class PostController < ApplicationController
  require 'carrierwave/orm/activerecord'
  before_action :authenticate_user!, only: [:show, :new, :create, :edit, :update, :destroy]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  
  def new
    @post = Post.new
    @categories = Category.all
  end
  
  def create
    post = Post.create(post_params)
    post.image = params[:image]
    post.save!

    redirect_to '/'
  end
  
  def show
    @review = Review.new
  end
  
  def edit
  end
  
  def update
    Post.update(post_params)
    redirect_to root_path
  end
  
  def destroy
    @post.destroy
    redirect_to root_path
  end
  
  def like_toggle
    like = Like.find_by(user_id: current_user.id, post_id: params[:id]) 
    
    if like.nil?
      Like.create(user_id: current_user.id, post_id: params[:id])
    else
      like.destroy
    end
    redirect_to :back
  end
  private
  
  def post_params
    params.require(:post).permit(:title, :content, :image, :category_id, :user_id)
    
  end
  
  def set_post
    @post = Post.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/interest_helper.rb
module InterestHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/match_helper.rb
module MatchHelper
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AWS Hackathon</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">
  <script type="text/javascript" src="http://code.jquery.com/jquery-3.2.0.min.js" ></script>
  <%= csrf_meta_tags %>
</head>
<body>
  <header id="gnb">
    <h1 id="branding">
      <a href="/"><%= image_tag "logo.png", width: "250" %></a>
      <!--<a href="/"><%#= image_tag "logo2.png", width: "100" %></a>-->
      <!--<div class="branding-bg"></div>-->
    </h1>
    <nav class="navbar">
      <ul class="<%#= 'white-ul' if current_page?(root_path) %>">
        <li><%= link_to "세상보기", home_list_path, class: "#{'current-nav' if current_page?(home_list_path)}" %></li>
        <li><%= link_to "세상후기", home_reviews_path, class: "#{'current-nav' if current_page?(home_reviews_path)}" %></li>  
        <% if user_signed_in? %>
          <li><strong><%= current_user.nickname %></strong> 님</li>
          <li><%= link_to "마이 페이지", mypage_mypost_path, class: "#{'current-nav' if current_page?(mypage_mypost_path)}" %></li>
          <li><%= link_to "로그아웃", destroy_user_session_path, method: :delete, data: {confirm: "로그아웃하시겠습니까?"}, class: "btn-logout" %></li>
        <% else %>
          <li><%= link_to "로그인", new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </header>
  <%= yield %>
  <footer>
    <p>©GirlsOnTop IT, All Rights Reserved. 2018.11.03.</p>
  </footer>
</body>
</html>